"""initial schema

Revision ID: 0a66f447f5fc
Revises: 
Create Date: 2026-09-02 10:45:33.811241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a66f447f5fc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_escalations',
    sa.Column('alert_id', sa.String(length=200), nullable=True),
    sa.Column('escalated_to_user_id', sa.String(length=200), nullable=True),
    sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_escalations_alert_id'), 'alert_escalations', ['alert_id'], unique=False)
    op.create_table('alerts',
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('severity', sa.Text(), nullable=True),
    sa.Column('vehicle_id', sa.String(length=200), nullable=True),
    sa.Column('order_id', sa.String(length=200), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_order_id'), 'alerts', ['order_id'], unique=False)
    op.create_index(op.f('ix_alerts_vehicle_id'), 'alerts', ['vehicle_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('actor_id', sa.Text(), nullable=True),
    sa.Column('action', sa.Text(), nullable=True),
    sa.Column('target_entity', sa.Text(), nullable=True),
    sa.Column('target_id', sa.Text(), nullable=True),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auth_events',
    sa.Column('user_id', sa.String(length=200), nullable=True),
    sa.Column('event_type', sa.Text(), nullable=True),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('communication_jobs',
    sa.Column('message_id', sa.String(length=200), nullable=True),
    sa.Column('queue_state', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('scheduled_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('idempotency_key', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communication_jobs_message_id'), 'communication_jobs', ['message_id'], unique=False)
    op.create_table('communication_preferences',
    sa.Column('user_id', sa.String(length=200), nullable=True),
    sa.Column('consent', sa.Boolean(), nullable=True),
    sa.Column('opt_out', sa.Boolean(), nullable=True),
    sa.Column('quiet_hours_start', sa.Text(), nullable=True),
    sa.Column('quiet_hours_end', sa.Text(), nullable=True),
    sa.Column('language', sa.Text(), nullable=True),
    sa.Column('fallback_rules_json', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communication_preferences_user_id'), 'communication_preferences', ['user_id'], unique=False)
    op.create_table('contact_methods',
    sa.Column('user_id', sa.String(length=200), nullable=True),
    sa.Column('method_type', sa.Text(), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('verification_state', sa.Text(), nullable=True),
    sa.Column('is_preferred', sa.Boolean(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_methods_user_id'), 'contact_methods', ['user_id'], unique=False)
    op.create_table('conversations',
    sa.Column('subject_type', sa.Text(), nullable=True),
    sa.Column('subject_id', sa.Text(), nullable=True),
    sa.Column('channel', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('phone', sa.BigInteger(), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('consent_status', sa.Boolean(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delivery_proofs',
    sa.Column('order_id', sa.String(length=200), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('signature_ref', sa.Text(), nullable=True),
    sa.Column('recipient_name', sa.Text(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_proofs_order_id'), 'delivery_proofs', ['order_id'], unique=False)
    op.create_table('drivers',
    sa.Column('user_id', sa.String(length=200), nullable=True),
    sa.Column('license_no', sa.Text(), nullable=True),
    sa.Column('preferred_channel', sa.Text(), nullable=True),
    sa.Column('current_vehicle_id', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('geofences',
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('zone_type', sa.Text(), nullable=True),
    sa.Column('polygon_json', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gps_trails',
    sa.Column('vehicle_id', sa.String(length=200), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('speed_kph', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gps_trails_vehicle_id'), 'gps_trails', ['vehicle_id'], unique=False)
    op.create_table('integration_status',
    sa.Column('provider', sa.Text(), nullable=True),
    sa.Column('state', sa.Text(), nullable=True),
    sa.Column('last_checked', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('load_manifests',
    sa.Column('route_id', sa.String(length=200), nullable=True),
    sa.Column('vehicle_id', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('cargo_type', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_load_manifests_route_id'), 'load_manifests', ['route_id'], unique=False)
    op.create_index(op.f('ix_load_manifests_vehicle_id'), 'load_manifests', ['vehicle_id'], unique=False)
    op.create_table('manifest_items',
    sa.Column('manifest_id', sa.String(length=200), nullable=True),
    sa.Column('cargo_category', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('temp_requirement_c', sa.Float(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manifest_items_manifest_id'), 'manifest_items', ['manifest_id'], unique=False)
    op.create_table('message_events',
    sa.Column('message_id', sa.String(length=200), nullable=True),
    sa.Column('event_type', sa.Text(), nullable=True),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_events_message_id'), 'message_events', ['message_id'], unique=False)
    op.create_table('messages',
    sa.Column('conversation_id', sa.String(length=200), nullable=True),
    sa.Column('direction', sa.Text(), nullable=True),
    sa.Column('channel', sa.Text(), nullable=True),
    sa.Column('provider_message_id', sa.Text(), nullable=True),
    sa.Column('template_id', sa.String(length=200), nullable=True),
    sa.Column('content_ref', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_table('notification_templates',
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('channel', sa.Text(), nullable=True),
    sa.Column('language', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('variables_json', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('optimization_run_routes',
    sa.Column('run_id', sa.BigInteger(), nullable=False),
    sa.Column('vehicle_id', sa.BigInteger(), nullable=False),
    sa.Column('distance', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('duration', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('risk', sa.Integer(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimization_run_routes_run_id'), 'optimization_run_routes', ['run_id'], unique=False)
    op.create_index(op.f('ix_optimization_run_routes_vehicle_id'), 'optimization_run_routes', ['vehicle_id'], unique=False)
    op.create_table('optimization_run_stops',
    sa.Column('run_id', sa.BigInteger(), nullable=False),
    sa.Column('vehicle_id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=True),
    sa.Column('stop_sequence', sa.Integer(), nullable=True),
    sa.Column('location_name', sa.Text(), nullable=True),
    sa.Column('lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('lng', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('eta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('slack_min', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimization_run_stops_order_id'), 'optimization_run_stops', ['order_id'], unique=False)
    op.create_index(op.f('ix_optimization_run_stops_run_id'), 'optimization_run_stops', ['run_id'], unique=False)
    op.create_index(op.f('ix_optimization_run_stops_vehicle_id'), 'optimization_run_stops', ['vehicle_id'], unique=False)
    op.create_table('optimization_runs',
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('mode', sa.Text(), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('data_snapshot', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_events',
    sa.Column('order_id', sa.String(length=200), nullable=True),
    sa.Column('event_type', sa.Text(), nullable=True),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_events_order_id'), 'order_events', ['order_id'], unique=False)
    op.create_table('orders',
    sa.Column('customer_id', sa.String(length=200), nullable=True),
    sa.Column('route_id', sa.String(length=200), nullable=True),
    sa.Column('vehicle_id', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('eta_window_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('eta_window_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cargo_temp_c', sa.Float(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_orders_route_id'), 'orders', ['route_id'], unique=False)
    op.create_index(op.f('ix_orders_vehicle_id'), 'orders', ['vehicle_id'], unique=False)
    op.create_table('roles',
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('permissions_json', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('route_stops',
    sa.Column('route_id', sa.String(length=200), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('location_name', sa.Text(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('arrival_window_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('arrival_window_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_route_stops_route_id'), 'route_stops', ['route_id'], unique=False)
    op.create_table('routes',
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('mode', sa.Text(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('duration_min', sa.Float(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('polyline_geojson', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('user_id', sa.String(length=200), nullable=True),
    sa.Column('login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('logout_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=200), nullable=True),
    sa.Column('device_info', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenant_scopes',
    sa.Column('user_id', sa.String(length=200), nullable=True),
    sa.Column('scope_type', sa.Text(), nullable=True),
    sa.Column('scope_value', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('phone', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('profile_photo_url', sa.Text(), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('vehicle_operating_profiles',
    sa.Column('vehicle_id', sa.BigInteger(), nullable=False),
    sa.Column('capacity_kg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('capacity_m3', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('temperature_capability', sa.Text(), nullable=True),
    sa.Column('shift_start', sa.Text(), nullable=True),
    sa.Column('shift_end', sa.Text(), nullable=True),
    sa.Column('cost_per_km', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cost_per_hour', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('depot_lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('depot_lng', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_operating_profiles_vehicle_id'), 'vehicle_operating_profiles', ['vehicle_id'], unique=False)
    op.create_table('vehicles',
    sa.Column('plate_no', sa.String(length=200), nullable=True),
    sa.Column('driver_id', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('fuel_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ignition_on', sa.Boolean(), nullable=True),
    sa.Column('current_lat', sa.Float(), nullable=True),
    sa.Column('current_lng', sa.Float(), nullable=True),
    sa.Column('heading', sa.Float(), nullable=True),
    sa.Column('speed_kph', sa.Float(), nullable=True),
    sa.Column('zone', sa.Text(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voice_calls',
    sa.Column('contact_id', sa.String(length=200), nullable=True),
    sa.Column('call_state', sa.Text(), nullable=True),
    sa.Column('intent', sa.Text(), nullable=True),
    sa.Column('transfer_result', sa.Text(), nullable=True),
    sa.Column('consent_flag', sa.Boolean(), nullable=True),
    sa.Column('recording_ref', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_calls_contact_id'), 'voice_calls', ['contact_id'], unique=False)
    op.create_table('warehouse',
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('zone', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('warehouse_events',
    sa.Column('warehouse_id', sa.String(length=200), nullable=True),
    sa.Column('event_type', sa.Text(), nullable=True),
    sa.Column('manifest_id', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouse_events_warehouse_id'), 'warehouse_events', ['warehouse_id'], unique=False)
    op.create_table('webhook_events',
    sa.Column('provider', sa.Text(), nullable=True),
    sa.Column('payload_ref', sa.Text(), nullable=True),
    sa.Column('signature_status', sa.Text(), nullable=True),
    sa.Column('processing_result', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('webhook_events')
    op.drop_index(op.f('ix_warehouse_events_warehouse_id'), table_name='warehouse_events')
    op.drop_table('warehouse_events')
    op.drop_table('warehouse')
    op.drop_index(op.f('ix_voice_calls_contact_id'), table_name='voice_calls')
    op.drop_table('voice_calls')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_vehicle_operating_profiles_vehicle_id'), table_name='vehicle_operating_profiles')
    op.drop_table('vehicle_operating_profiles')
    op.drop_table('users')
    op.drop_table('tenant_scopes')
    op.drop_table('sessions')
    op.drop_table('routes')
    op.drop_index(op.f('ix_route_stops_route_id'), table_name='route_stops')
    op.drop_table('route_stops')
    op.drop_table('roles')
    op.drop_index(op.f('ix_orders_vehicle_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_route_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_order_events_order_id'), table_name='order_events')
    op.drop_table('order_events')
    op.drop_table('optimization_runs')
    op.drop_index(op.f('ix_optimization_run_stops_vehicle_id'), table_name='optimization_run_stops')
    op.drop_index(op.f('ix_optimization_run_stops_run_id'), table_name='optimization_run_stops')
    op.drop_index(op.f('ix_optimization_run_stops_order_id'), table_name='optimization_run_stops')
    op.drop_table('optimization_run_stops')
    op.drop_index(op.f('ix_optimization_run_routes_vehicle_id'), table_name='optimization_run_routes')
    op.drop_index(op.f('ix_optimization_run_routes_run_id'), table_name='optimization_run_routes')
    op.drop_table('optimization_run_routes')
    op.drop_table('notification_templates')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_message_events_message_id'), table_name='message_events')
    op.drop_table('message_events')
    op.drop_index(op.f('ix_manifest_items_manifest_id'), table_name='manifest_items')
    op.drop_table('manifest_items')
    op.drop_index(op.f('ix_load_manifests_vehicle_id'), table_name='load_manifests')
    op.drop_index(op.f('ix_load_manifests_route_id'), table_name='load_manifests')
    op.drop_table('load_manifests')
    op.drop_table('integration_status')
    op.drop_index(op.f('ix_gps_trails_vehicle_id'), table_name='gps_trails')
    op.drop_table('gps_trails')
    op.drop_table('geofences')
    op.drop_table('drivers')
    op.drop_index(op.f('ix_delivery_proofs_order_id'), table_name='delivery_proofs')
    op.drop_table('delivery_proofs')
    op.drop_table('customers')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_contact_methods_user_id'), table_name='contact_methods')
    op.drop_table('contact_methods')
    op.drop_index(op.f('ix_communication_preferences_user_id'), table_name='communication_preferences')
    op.drop_table('communication_preferences')
    op.drop_index(op.f('ix_communication_jobs_message_id'), table_name='communication_jobs')
    op.drop_table('communication_jobs')
    op.drop_table('auth_events')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_alerts_vehicle_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_order_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_alert_escalations_alert_id'), table_name='alert_escalations')
    op.drop_table('alert_escalations')
    # ### end Alembic commands ###
